services:
  backend:
    image: node:12-alpine
    command: sh -c "yarn install && yarn run start"
    ports:
    - 3000:3000
    working_dir: /teamway-backend
    volumes: 
    - ./:/teamway-backend
